INSERT INTO LIDL (Meno, Typ, Cena, Balenie) VALUES ('Chlieb', 'Pecivo', 1.5, 'ks');
INSERT INTO LIDL (Meno, Typ, Cena, Balenie) VALUES ('Jablko', 'Ovocie', 0.79, 'kg');
INSERT INTO LIDL (Meno, Typ, Cena, Balenie) VALUES ('Mrkva', 'Zelenina', 0.59, 'kg');
INSERT INTO LIDL (Meno, Typ, Cena, Balenie) VALUES ('Hruska', 'Ovocie', 0.89, 'kg');
INSERT INTO LIDL (Meno, Typ, Cena, Balenie) VALUES ('Slivka', 'Ovocie', 0.7, 'kg');
INSERT INTO LIDL (Meno, Typ, Cena, Balenie) VALUES ('Rozok', 'Pecivo', 0.06, 'ks');
INSERT INTO LIDL (Meno, Typ, Cena, Balenie) VALUES ('Cibula', 'Zelenina', 0.6, 'kg');
INSERT INTO LIDL (Meno, Typ, Cena, Balenie) VALUES ('Stehno - kuracie', 'Maso', 2.3, 'kg');
INSERT INTO LIDL (Meno, Typ, Cena, Balenie) VALUES ('Stehno - morcacie', 'Maso', 3.69, 'kg');
INSERT INTO LIDL (Meno, Typ, Cena, Balenie) VALUES ('Stehno - bravcove', 'Maso', 4.19, 'kg');
INSERT INTO LIDL (Meno, Typ, Cena, Balenie) VALUES ('Pomelo', 'Ovocie', 2.59, 'ks');
INSERT INTO LIDL (Meno, Typ, Cena, Balenie) VALUES ('Granatove jablko', 'Ovocie', 0.99, 'ks');
INSERT INTO LIDL (Meno, Typ, Cena, Balenie) VALUES ('Sunka - kuracia', 'Maso', 7.16, 'kg');
INSERT INTO LIDL (Meno, Typ, Cena, Balenie) VALUES ('Sunka - morcacia', 'Maso', 10.38, 'kg');
INSERT INTO LIDL (Meno, Typ, Cena, Balenie) VALUES ('Tlacenka - bravcova', 'Maso', 4.57, 'kg');
INSERT INTO LIDL (Meno, Typ, Cena, Balenie) VALUES ('Tlacenka - kuracia', 'Maso', 5.36, 'kg');
INSERT INTO LIDL (Meno, Typ, Cena, Balenie) VALUES ('Zemiak', 'Zelenina', 0.49, 'kg');
INSERT INTO LIDL (Meno, Typ, Cena, Balenie) VALUES ('Pomaranc', 'Ovocie', 0.89, 'kg');
INSERT INTO LIDL (Meno, Typ, Cena, Balenie) VALUES ('Makovnik', 'Pecivo', 1.79, 'ks');