INSERT INTO KAUFLAND (Meno, Typ, Cena, Balenie) VALUES ("Cibula", "ZEL", 0.58, "kg");
INSERT INTO KAUFLAND (Meno, Typ, Cena, Balenie) VALUES ("Tlacenka - bravcova", "MAS", 4.4, "kg");
INSERT INTO KAUFLAND (Meno, Typ, Cena, Balenie) VALUES ("Makovnik", "PEC", 3.8, "kg");
INSERT INTO KAUFLAND (Meno, Typ, Cena, Balenie) VALUES ("Paprika", "ZEL", 0.89, "kg");
INSERT INTO KAUFLAND (Meno, Typ, Cena, Balenie) VALUES ("Slivka", "OVO", 0.75, "kg");
INSERT INTO KAUFLAND (Meno, Typ, Cena, Balenie) VALUES ("Rozok", "PEC", 0.06, "ks");
INSERT INTO KAUFLAND (Meno, Typ, Cena, Balenie) VALUES ("Sunka - kuracia", "MAS", 6.3, "kg");
INSERT INTO KAUFLAND (Meno, Typ, Cena, Balenie) VALUES ("Sunka - bravcova", "MAS", 5.7, "kg");
INSERT INTO KAUFLAND (Meno, Typ, Cena, Balenie) VALUES ("Zemiak", "ZEL", 0.05, "ks");
INSERT INTO KAUFLAND (Meno, Typ, Cena, Balenie) VALUES ("Pomaranc", "OVO", 0.72, "kg");
INSERT INTO KAUFLAND (Meno, Typ, Cena, Balenie) VALUES ("Chlieb", "PEC", 1.49, "ks");
INSERT INTO KAUFLAND (Meno, Typ, Cena, Balenie) VALUES ("Granatove jablko", "OVO", 1.09, "ks");
INSERT INTO KAUFLAND (Meno, Typ, Cena, Balenie) VALUES ("Jablko", "OVO", 0.79, "kg");
INSERT INTO KAUFLAND (Meno, Typ, Cena, Balenie) VALUES ("Mrkva", "ZEL", 0.59, "kg");
INSERT INTO KAUFLAND (Meno, Typ, Cena, Balenie) VALUES ("Hruska", "OVO", 0.89, "kg");